### ISSUE TITLE
is alert state possible

### ISSUE THREAD

**Issue by ypapax** [martini-contrib/gorelic#3]
In what cases plugin `gorelic` will open alert? As I see it always has green state. There is no `apdex` score and error rate.

**Comment by yvasiyarov** [comment]
@ypapax you should configure alerts yourself. Click on this icon:
![](https://dl.dropboxusercontent.com/spa/lgp0ds3s8slxwos/55s_d-rv.png)
You will see popup there you can configure alert policy

**Comment by ypapax** [comment]
Thank you
